api/urls.py
from django.urls import path

from .views import CryptoList, CryptoDetail

urlpatterns = [
    # Cryptocurrency detail info
    path('<str:symbol>/', CryptoDetail.as_view(), name="crypto_detail"),

    # List of all cryptocurrencies
    path('', CryptoList.as_view(), name="crypto_list"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # Django admin panel
    path('admin/', admin.site.urls),

    # User accounts
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),

    # API
    path('api/v1/', include('api.urls')),
    path('api-auth/', include('rest_framework.urls')),

    # Local
    path('', include('cryptocurrency.urls')),
]

cryptocurrency/urls.py
from django.urls import path

from .views import index_view, search_cryptocurrency, add_to_favorite, remove_from_favorites, favorites_list, news_list

app_name = 'cryptocurrency'
urlpatterns = [
    # Index page (List of all cryptocurrencies)
    path('', index_view, name='index'),

    # Search page
    path('search/', search_cryptocurrency, name='search'),

    # Favorites cryptos (list, add, remove)
    path('favorites/', favorites_list, name='favorites_list'),
    path('add_favorite/<int:crypto_id>/', add_to_favorite, name='add_favorite'),
    path('remove_favorite/<int:crypto_id>/',
         remove_from_favorites, name='remove_favorite'),

    # News page
    path('news/', news_list, name='news'),
]

templates/include/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary shadow">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="{% url 'cryptocurrency:index' %}" style="color: var(--bs-primary);">Crypto</a>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'cryptocurrency:index' %}" style="color: var(--bs-primary-text);">Актуальное</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'cryptocurrency:news' %}" style="color: var(--bs-primary-text);">Новости</a>
        </li>
        {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link active" href="{% url 'cryptocurrency:favorites_list' %}" style="color: var(--bs-primary-text);">Избранные криптовалюты</a>
            </li>
        {% endif %}
      </ul>
      <form class="d-flex" action="{% url 'cryptocurrency:search' %}" method="get">
        <input class="form-control me-2" type="text" name="q" placeholder="Найти криптовалюту...">
        <button class="btn btn-outline-primary me-2" type="submit">Поиск</button>
      </form>
      {% if user.is_authenticated %}
        {% if user.is_staff %}
            <button class="btn btn-primary me-2" onclick="location.href='{% url 'admin:index' %}'" type="button">Панель администратора</button>
        {% endif %}
        <button class="btn btn-primary me-2" onclick="location.href='{% url 'logout' %}'" type="button">Выход</button>
      {% else %}
        <button class="btn btn-primary me-2" onclick="location.href='{% url 'login' %}'" type="button">Авторизация</button>
        <button class="btn btn-primary me-2" onclick="location.href='{% url 'signup' %}'" type="button">Регистрация</button>
      {% endif %}
    </div>
  </div>
</nav>