api/urls.py
from django.urls import path

from .views import CryptoList, CryptoDetail

urlpatterns = [
    # Cryptocurrency detail info
    path('<str:symbol>/', CryptoDetail.as_view(), name="crypto_detail"),

    # List of all cryptocurrencies
    path('', CryptoList.as_view(), name="crypto_list"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # Django admin panel
    path('admin/', admin.site.urls),

    # User accounts
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),

    # API
    path('api/v1/', include('api.urls')),
    path('api-auth/', include('rest_framework.urls')),

    # Local
    path('', include('cryptocurrency.urls')),
]

cryptocurrency/urls.py
from django.urls import path

from .views import index_view, search_cryptocurrency, add_to_favorite, remove_from_favorites, favorites_list, news_list

app_name = 'cryptocurrency'
urlpatterns = [
    # Index page (List of all cryptocurrencies)
    path('', index_view, name='index'),

    # Search page
    path('search/', search_cryptocurrency, name='search'),

    # Favorites cryptos (list, add, remove)
    path('favorites/', favorites_list, name='favorites_list'),
    path('add_favorite/<int:crypto_id>/', add_to_favorite, name='add_favorite'),
    path('remove_favorite/<int:crypto_id>/',
         remove_from_favorites, name='remove_favorite'),

    # News page
    path('news/', news_list, name='news'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru" data-bs-theme="light">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'img/favicon.svg' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <title>{% block title %}{% endblock title %} - Crypto</title>
  </head>
  <body>
    {% include 'include/navbar.html' %}
    {% block content %}
    {% endblock content %}
    <script src="{% static 'js/bootstrap.bundle.js' %}"></script>
  </body>
</html>

templates/favorites_list.html
{% extends 'base.html' %}
{% load humanize %}

{% block title %}Избранное{% endblock title %}

{% block content %}
<div class="container mt-5 mb-5">
    <h1>Избранные криптовалюты</h1>
    В этом разделе перечислены ваши избранные криптовалюты.
    {% if favorites_list %}
        <div class="table-responsive">
            <table class="table table-striped table-hover align-middle caption-top">
                <caption>Данные предоставлены с сайта <a class="text-secondary" href="https://coinmarketcap.com/">coinmarketcap.com</a>.</caption>
                <thead class="table-dark">
                    <tr class="text-center">
                        <th scope="col">#</th>
                        <th scope="col">Название</th>
                        <th scope="col">Символьный код</th>
                        <th scope="col">Текущий курс</th>
                        <th scope="col">1ч %</th>
                        <th scope="col">24ч %</th>
                        <th scope="col">7д %</th>
                        <th scope="col">Объем торгов</th>
                        <th scope="col">Рыночная капитализация</th>
                        <th scope="col">Избранное</th>
                    </tr>
                </thead>
                <tbody class="table-group-divider">
                    {% for favorite in favorites_list %}
                        <tr>
                            <th scope="row" class="text-center">{{ favorite.id }}</th>
                            <th class="text-center">{{ favorite.name }}</th>
                            <th class="text-center">{{ favorite.symbol }}</th>
                            <th class="text-center">{{ favorite.price|intcomma }}$</th>
                            <th class="text-center" {% if favorite.percent_change_1h < 0 %} style="color: var(--bs-danger);" {% else %} style="color: var(--bs-success);" {% endif %}>{{ favorite.percent_change_1h }}%</th>
                            <th class="text-center" {% if favorite.percent_change_24h < 0 %} style="color: var(--bs-danger);" {% else %} style="color: var(--bs-success);" {% endif %}>{{ favorite.percent_change_24h }}%</th>
                            <th class="text-center" {% if favorite.percent_change_7d < 0 %} style="color: var(--bs-danger);" {% else %} style="color: var(--bs-success);" {% endif %}>{{ favorite.percent_change_7d }}%</th>
                            <th class="text-center">{{ favorite.volume|intcomma }}$</th>
                            <th class="text-center">{{ favorite.market_cap|intcomma }}$</th>
                            <th class="text-center"><a style="text-decoration: none; color: var(--bs-danger);" href="{% url 'cryptocurrency:remove_favorite' favorite.id %}">Удалить из избранного</a></th>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    {% else %}
        <h4 class="mt-5">Вы еще не начали отслеживать криптовалюты.</h4>
    {% endif %}
</div>
{% endblock content %}

templates/index.html
{% extends 'base.html' %}
{% load humanize %}

{% block title %}Главная{% endblock title %}

{% block content %}
<div class="container mt-5 mb-5">
    <h1>Информация о криптовалютах</h1>
    {% if user.is_authenticated %}
        Вы авторизованы как {{ user.username }}.<br>
        В таблице ниже можно ознакомиться с информацией о криптовалютах.
    {% else %}
        Вы не авторизованы.
    {% endif %}
    <div class="table-responsive">
        <table class="table table-striped table-hover align-middle caption-top">
            <caption>Данные предоставлены с сайта <a class="text-secondary" href="https://coinmarketcap.com/">coinmarketcap.com</a>.</caption>
            <thead class="table-dark">
                <tr class="text-center">
                    <th scope="col">#</th>
                    <th scope="col">Название</th>
                    <th scope="col">Символьный код</th>
                    <th scope="col">Текущий курс</th>
                    <th scope="col">1ч %</th>
                    <th scope="col">24ч %</th>
                    <th scope="col">7д %</th>
                    <th scope="col">Объем торгов</th>
                    <th scope="col">Рыночная капитализация</th>
                    {% if user.is_authenticated %}
                    <th scope="col">Избранное</th>
                    {% endif %}
                </tr>
            </thead>
            <tbody class="table-group-divider">
                {% for crypto in crypto_list %}
                    <tr>
                        <th scope="row" class="text-center">{{ crypto.id }}</th>
                        <th class="text-center">{{ crypto.name }}</th>
                        <th class="text-center">{{ crypto.symbol }}</th>
                        <th class="text-center">{{ crypto.price|intcomma }}$</th>
                        <th class="text-center" {% if crypto.percent_change_1h < 0 %} style="color: var(--bs-danger);" {% else %} style="color: var(--bs-success);" {% endif %}>{{ crypto.percent_change_1h }}%</th>
                        <th class="text-center" {% if crypto.percent_change_24h < 0 %} style="color: var(--bs-danger);" {% else %} style="color: var(--bs-success);" {% endif %}>{{ crypto.percent_change_24h }}%</th>
                        <th class="text-center" {% if crypto.percent_change_7d < 0 %} style="color: var(--bs-danger);" {% else %} style="color: var(--bs-success);" {% endif %}>{{ crypto.percent_change_7d }}%</th>
                        <th class="text-center">{{ crypto.volume|intcomma }}$</th>
                        <th class="text-center">{{ crypto.market_cap|intcomma }}$</th>
                        {% if user.is_authenticated %}
                            {% if crypto in favorites_list %}
                                <th class="text-center"><a style="text-decoration: none; color: var(--bs-danger);" href="{% url 'cryptocurrency:remove_favorite' crypto.id %}">Удалить из избранного</a></th>
                            {% else %}
                                <th class="text-center"><a style="text-decoration: none; color: var(--bs-warning);" href="{% url 'cryptocurrency:add_favorite' crypto.id %}">Добавить в избранное</a></th>
                            {% endif %}
                        {% endif %}
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock content %}

templates/news.html
{% extends 'base.html' %}

{% block title %}Новости{% endblock title %}

{% block content %}
<div class="container mt-5 mb-5">
    <h1>Новости криптовалют</h1>
    В этом разделе можно ознакомиться с новостями криптовалют.
    <p class="text-secondary mt-2">Все новости предоставлены с помощью <a href="https://newsapi.org/" class="text-secondary">NewsAPI</a>.</p>
    {% for news in news_list %}
        <div class="card mb-3">
            <div class="card-header">
                {% if news.author %}
                    Автор статьи: {{ news.author }} | Опубликовано: {{ news.published_at }}
                {% else %}
                    Автор не найден
                {% endif %}
            </div>
            <div class="card-body">
                <h4 class="card-title">{{ news.title }}</h4>
                {% if news.url_to_image %}
                    <img src="{{ news.url_to_image }}" alt="{{ news.title }}" class="mx-auto d-block rounded mt-2" style="max-width: 600px; max-height: 600px">
                {% endif %}
                <p class="card-text mt-2">{{ news.description }}</p>
            </div>
            <div class="card-footer">
                <a href="{{ news.url }}" style="text-decoration: none;">Читать полностью...</a>
            </div>
        </div>
    {% endfor %}
</div>
{% endblock content %}

templates/search.html
{% extends 'base.html' %}
{% load humanize %}

{% block title %}Поиск{% endblock title %}

{% block content %}
<div class="container mt-5 mb-5">
    <h1>Результаты поиска</h1>
    Ниже приведены результаты поиска по вашему запросу: "{{ query }}".<br>
    Обратите внимание, что поиск осуществляется по символьному коду криптовалюты или ее названию.
    {% if crypto_list %}
        <div class="table-responsive">
            <table class="table table-striped table-hover align-middle caption-top">
                <caption>Данные предоставлены с сайта <a class="text-secondary" href="https://coinmarketcap.com/">coinmarketcap.com</a>.</caption>
                <thead class="table-dark">
                    <tr class="text-center">
                        <th scope="col">#</th>
                        <th scope="col">Название</th>
                        <th scope="col">Символьный код</th>
                        <th scope="col">Текущий курс</th>
                        <th scope="col">1ч %</th>
                        <th scope="col">24ч %</th>
                        <th scope="col">7д %</th>
                        <th scope="col">Объем торгов</th>
                        <th scope="col">Рыночная капитализация</th>
                    </tr>
                </thead>
                <tbody class="table-group-divider">
                    {% for crypto in crypto_list %}
                        <tr>
                            <th scope="row" class="text-center">{{ crypto.id }}</th>
                            <th class="text-center">{{ crypto.name }}</th>
                            <th class="text-center">{{ crypto.symbol }}</th>
                            <th class="text-center">{{ crypto.price|intcomma }}$</th>
                            <th class="text-center" {% if crypto.percent_change_1h < 0 %} style="color: var(--bs-danger);" {% else %} style="color: var(--bs-success);" {% endif %}>{{ crypto.percent_change_1h }}%</th>
                            <th class="text-center" {% if crypto.percent_change_24h < 0 %} style="color: var(--bs-danger);" {% else %} style="color: var(--bs-success);" {% endif %}>{{ crypto.percent_change_24h }}%</th>
                            <th class="text-center" {% if crypto.percent_change_7d < 0 %} style="color: var(--bs-danger);" {% else %} style="color: var(--bs-success);" {% endif %}>{{ crypto.percent_change_7d }}%</th>
                            <th class="text-center">{{ crypto.volume|intcomma }}$</th>
                            <th class="text-center">{{ crypto.market_cap|intcomma }}$</th>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    {% else %}
        <h4 class="mt-5">По вашему запросу ничего не найдено.</h4>
    {% endif %}
</div>
{% endblock content %}